[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "LMTodo"
version = "0.1.0"
description = "A TODO list application in Python"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Luciano Magri", email = "cazzbr@gmail.com" }
]
license = "GPL-2.0-only"
license-files = ["LICENSE"]
keywords = ["todo", "productivity", "python"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black",
    "isort"
]

[tool.setuptools.packages.find]
where = ["src"]
